#!/bin/bash
# Starts an infinite While Loop
while :
do
#Lists the options that the user can pick from
echo 'What do you need to do:' ; echo '1) Network scan' ; echo '2) Port Scan' ; echo '3) Service / OS Scan' ; echo '4) quit'
#'read' will allow the user to input characters and store them in the variable 'choice'
read choice
# If statement that checks if 'choice is equal to 1'
if (( $choice == 1 )); then
#Asks the user what IPs they want to input as well as the format to write them in
echo -e "\nWhat IP range do you want to scan? Ex. XXX.XXX.XXX.XXX/X"
#reads what the user typed and stores it in 'IP'
read IP
echo -e "\nOne moment please."
#nmap uses the IPs the user selected from 'IP' and quickly runs a scan. That is piped to a grep that pulls only the IP addresses out and      
     writes them to a file in the current working directory 'IPS.txt'
sudo nmap $IP -T3 --min-rate 8000| grep -E -o '([0-9]{1,3}\.){3}[0-9]{1,3}' > ./NmapIps.txt
#Makes a short loading sequence
sleep 1 ; echo -e ".\n" ; sleep 1 ; echo -e "..\n" ; sleep 1 ; echo -e "...\n"
#Tells the user the absolute path to the file 'IPS.txt'. The '~+' has the find command search in the absolute path of the cwd.
echo -e "\nPrinted to $(find ~+ -name '*Ips.txt')\n"
elif (( $choice == 2 )); then
echo -e "\nPlease enter an IP address / Range of IPs. Ex. XXX.XXX.XXX.XXX/X"
read IP
echo -e "\nPlease enter what ports you want to scan. Ex. X-X,X,X-X"
read port
echo -e "\nOne moment please..."
sudo nmap $IP -p $port -T3 --min-rate 8000 | grep -E 'Nmap scan|PORT|/tcp' > ./NmapPorts.txt
sleep 1 ; echo -e ".\n" ; sleep 1 ; echo -e "..\n" ; sleep 1 ; echo -e "...\n"
echo -e "\nPrinted to $(find ~+ -name '*Ports.txt')\n"
elif (( $choice == 3 )); then
echo -e "\nPlease enter an IP address / Range of IPs. Ex. XXX.XXX.XXX.XXX/X"
read IP
echo -e "\nPlease enter what ports you want to scan. Ex. X-X,X,X-X"
read port
echo -e "\nOne moment please..."
sudo nmap -sV -O  $IP -p $port -T3 --min-rate 8000 |  grep -E 'Nmap scan|PORT|/tcp|/udp|Service' > ./NmapServices.txt 
sleep 1 ; echo -e ".\n" ; sleep 1 ; echo -e "..\n" ; sleep 1 ; echo -e "...\n"
echo -e "\nPrinted to $(find ~+ -name '*Services.txt')\n"
elif (( $choice == 4 )); then
echo -e "\nThank you for your time !\n"
break
else
echo -e "\nThat wasn't an option. >:(\n"
fi
done
