#!/bin/bash
while :
do
echo -e "\nEnter IP Ex. (xxx.xxx.xxx.xxx/xx)"
read IP
echo -e "\nEnter Ports or leave blank for default ports. Ex. (xx-xx,xx,xx)"
read port
sudo nmap -sn $IP -T3 --min-rate 8000 | grep -E -o '([0-9]{1,3}\.){3}[0-9]{1,3}' > ./NmapIps.txt
# checks if the variable 'port' is NULL
if [ -z "$port" ]; then
sudo nmap -sV -O -Pn -iL ./NmapIps.txt -T3 --min-rate 8000 | grep -E 'Nmap scan|PORT|/tcp|/udp|Service' > ./NmapService.txt
else 
sudo nmap -sV -O -Pn -iL ./NmapIps.txt -p $port -T3 --min-rate 8000 | grep -E 'Nmap scan|PORT|/tcp|/udp|Service' > ./NmapService.txt
fi
#Will do a task pulling variable values from a file. the variable will be called 'line'
while IFS="" read -r line
do
#Checks if the string 'scan report' is in the variable 'line'
if [[ $line == *"scan report"* ]]; then
echo -e "\n$line"
else
echo -e "$line"
fi
#Selects the /NmapService.txt file to be used during the While loop
done < ./NmapService.txt
figlet"TYFYS" | lolcat
done
